services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./static:/app/static
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - ghost

  ghost:
    image: ghost:5-alpine
    restart: always
    environment:
      # We use SQLite for easy development, but you might want to configure Postgres for production
      database__client: sqlite3
      database__connection__filename: content/data/ghost.db
      database__useNullAsDefault: "true"
      database__debug: "false"
      # URL needs to match the host:port that will be accessing the CMS
      url: https://ghost.juche.study # Change this to your production URL if applicable
    volumes:
      - ghost_data:/var/lib/ghost/content

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  ghost_data:
